spring.application.name=TasksApplication

server.port=8080


spring.datasource.url=jdbc:h2:mem:TaskApplication
spring.datasource.driverClassName=org.h2.Driver

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console