CREATE TABLE users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(255),
    last_name VARCHAR(255),
    email VARCHAR(255) NOT NULL UNIQUE,
    registration_date TIMESTAMP NOT NULL
);

CREATE TABLE tasks (
    task_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_text VARCHAR(1000) NOT NULL,
    due_date TIMESTAMP,
    creation_date TIMESTAMP NOT NULL,
    is_complete BOOLEAN NOT NULL,
    user_id_ref BIGINT NOT NULL,
    is_deleted BOOLEAN NOT NULL,
    CONSTRAINT fk_task_user FOREIGN KEY (user_id_ref) REFERENCES users(user_id)
);

CREATE TABLE notifications (
    notification_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text VARCHAR(1000) NOT NULL,
    date TIMESTAMP NOT NULL,
    task_id_fk BIGINT NOT NULL,
    user_id_fk BIGINT NOT NULL,
    is_read BOOLEAN NOT NULL,
    CONSTRAINT fk_notification_task FOREIGN KEY (task_id_fk) REFERENCES tasks(task_id),
    CONSTRAINT fk_notification_user FOREIGN KEY (user_id_fk) REFERENCES users(user_id)
);

CREATE INDEX idx_task_user_id ON tasks(user_id_ref);
CREATE INDEX idx_notification_task_id ON notifications(task_id_fk);
CREATE INDEX idx_notification_user_id ON notifications(user_id_fk);